# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b7b7f2808ca75d4e67d83b7f18d7cfb2c930b14115caf33df53459dd83b876c16781695d764a2807c3efab0c26d61a2fbfee0a16e2bf72763ae5e191b1eb979

test:
  secret_key_base: 6231d96482715a99c7de0a6b6810f5502de121ede29bf270ce3adf521e7a331cf44956270e2f443ca189735bc369b056e8cb5fb59b8aa9cf2ce1be2727121bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
